version: '3'

services:

  mysql_pwa_6522:
    image: mysql
    container_name: mysql_pwa_6522
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: utn
    volumes:
      - ./mysql/data/pwa_6522:/var/lib/mysql
      - ./mysql/init/mysql_pwa_6522-init.sql:/docker-entrypoint-initdb.d/mysql_pwa_6522-init.sql:ro

      
  phpmyadmin_pwa_6522:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_pwa_6522
    restart: always
    ports:
      - 3000:80
    environment:
      PMA_HOST: mysql_pwa_6522
      PMA_PORT: 3306
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: mysql.pwa6522.jhoacar.me
      LETSENCRYPT_HOST: mysql.pwa6522.jhoacar.me
      LETSENCRYPT_EMAIL: jhoacar.utn@gmail.com
    depends_on:
      - mysql_pwa_6522

  mongo_pwa_6522:
    image: mongo:4.4-focal
    container_name: mongo_pwa_6522
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongo/data/pwa_6522:/data/db
      - ./mongo/init/mysql_pwa_6522-init.sql:/docker-entrypoint-initdb.d/mysql_pwa_6522-init.sql:ro

  mongo_express_utn:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo_express_utn
    restart: always
    ports:
      - 3001:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo_pwa_6522:27017/
      VIRTUAL_PORT: 8081
      VIRTUAL_HOST: mongo.pwa6522.jhoacar.me
      LETSENCRYPT_HOST: mongo.pwa6522.jhoacar.me
      LETSENCRYPT_EMAIL: jhoacar.utn@gmail.com
    depends_on:
      - mongo_pwa_6522
