version: '3'

services:

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx_proxy_utn
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy/certs:/etc/nginx/certs:ro
      - ./proxy/vhostd:/etc/nginx/vhost.d
      - ./proxy/html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx_proxy_ssl_utn
    restart: always
    environment:
      DEFAULT_EMAIL: carrerojhoan@gmail.com
      NGINX_PROXY_CONTAINER: nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./proxy/certs:/etc/nginx/certs:rw
      - ./proxy/vhostd:/etc/nginx/vhost.d
      - ./proxy/html:/usr/share/nginx/html
      - ./proxy/acme:/etc/acme.sh

  mysql:
    image: mysql
    container_name: mysql_utn
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: utn
    volumes:
      # - ./mysql/data:/var/lib/mysql
      - mysql:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d:ro

      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_utn
    restart: always
    expose:
      - 80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: mysql.utn.jhoacar.me
      LETSENCRYPT_HOST: mysql.utn.jhoacar.me
      LETSENCRYPT_EMAIL: jhoacar.utn@gmail.com
    depends_on:
      - mysql

  mongo:
    image: mongo:4.4-focal
    container_name: mongo_utn
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      # - ./mongo/data:/data/db
      - mongo:/data/db
      - ./mongo/init:/docker-entrypoint-initdb.d:ro

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo_express_utn
    restart: always
    expose:
      - 8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      VIRTUAL_PORT: 8081
      VIRTUAL_HOST: mongo.utn.jhoacar.me
      LETSENCRYPT_HOST: mongo.utn.jhoacar.me
      LETSENCRYPT_EMAIL: jhoacar.utn@gmail.com
    depends_on:
      - mongo

#Use MOUNT volume because Mongo need permissions in the system NTFS
volumes:
  mongo:
    external: false 
  mysql:
    external: false 