export const CHANGE_NAME = 'Cambiar el nombre'
export const CHANGE_EMAIL = 'Cambiar el correo'
export const CHANGE_PASSWORD = 'Cambiar la contraseña'
export const CHANGE_AVATAR = 'Cmabiar el avatar'
export const CHANGE_IMAGE = 'Cambiar la imagen'
export const CHANGE_AVATAR_AND_IMAGE = 'Cambiar avatar e imagen'